/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DIDRegistry } from "./DIDRegistry";
export type { FBTC } from "./FBTC";
export type { FTSO } from "./FTSO";
export type { MicroLender } from "./MicroLender";
export type { RedFlagNFT } from "./RedFlagNFT";
